### ISSUE TITLE
项目路径真乱，根本不是拖进来一个文件夹的事

### ISSUE THREAD

**Issue by zzyyzz1992** [Roxasora/RxWebViewController#3]
另外，有两个RxWebViewController文件夹。

**Comment by zzyyzz1992** [comment]
另外下载下来都 build fail，上传前麻烦仔细看看吧

**Comment by Roxasora** [comment]
@zzyyzz1992 非常感谢提出这些问题！！确实之前更新的匆忙都没有检查过细节，就这样放上来真的是有很不负责，我已经清理了项目并且解决了编译错误！！再次感谢！！
