### ISSUE TITLE
偶尔pop出RxWebViewCotroller的问题

### ISSUE THREAD

**Issue by ghost** [Roxasora/RxWebViewController#7]
fix bug

**Comment by rushairer** [comment]
在新开ViewController里自己用     [self.navigationController popViewControllerAnimated:YES];
就不会触发  -(BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item

用系统的返回就没事。

纯代码写的  不用xib

**Comment by stattrak-dragonlore** [comment]
遇到楼主的问题 +1

**Comment by CoderYuChong** [comment]
我也遇到这个问题了，忘作者早日解决这个问题

**Comment by AsTryE** [comment]
出现类似问题，自定义导航栏继承自RxWebViewNavigationViewController，有些界面，push进入后，点击左上角返回按钮，返回按钮消失，界面还是在原来的界面，并没有pop到上一界面。不过用手势可以返回到上一个界面。但是再触发任何push的事件，进入新的界面后，点击左上角返回按钮都会出现之前的问题。我用了FDFullscreenPopGesture这个框架的，是否产生冲突？
